<p>Tai daugelio žaidėjų vaidmenų žaidimas, kurį galite žaisti tiesiog naršyklėje, svarbu kad naršyklė palaikytų javascript.</p>

<p>Žaidimas jus nukels į gana tolimą ateitį, į tą momentą, kai žmonės bandydami apgyvendinti planetą pavadinimų Signa susidurė su rjalais, kurie taip pat kolonizavo šią planetą. Deje, rjalai instinktų ir baimės vedami naikina svetimas rases, nes bijo, kad kitos civilizacijos gali juos pačius sunaikinti. Jie vadovaujasi taktika: "puolimas - geriausia ginyba". Taip  prasidėjo ilgas karas tarp abiejų rasių dėl dominavimo planetoje.</p>

<p>Rjalai dvikojos butybės panašios į žmonės. Nors jų technologijos mažiau pažengusios, tačiau jie remiasi fizinę jėga, kurios, beabejo, turi daugiau. Žmonės kovodami daugiausia naudojasi technologijomis. Netgi egzistuoja posakis tarp kareivių: "Jeigu leidi rjalui prisiartinti, iš tavęs neliks nė šlapios vietos". Tačiau žmonės pradėjo gaminitis kietesnius egzoskeletus, tvirtesnius pastatus, daugiau skraidyti negu judėti žeme, ir taip žmonės atsilaiko prieš rjalus.</p>

<p>Tu pradėdamas žaisti turėsi pasirinkti žmones arba rjalus. Žaidimo eigoje savo pasirinkimo keisti negalėsi, tad rinkdamasis turi nuspręsti, ar tu mėgsti kovoti akis į akį (rjalai), ar daryti gudrias atakas ir nugalėti priešą iš tolo (žmonės).</p>

<p>Kaip ir visi neworld kurti žaidimai, taip ir šis užtikrina jokių resetų, wipe, roundų. Taigi visada galėsi tobulinti savo veikėją. Išimtys taikomos jeigu įvyktų kokia nors katastrofa, sudegtų serveris ir atsarginių kopijų serveris, arba tiesiog atskirstu rjalai į žemę ir sunaikintų duomenų centrą.</p>

<div style="margin-top:30px">
	<div class="imagebox"><img alt="rjalas" src="/img/rjal.jpg" style="width:210px;height:210px" /><br /><br />Rjalas</div>
	<div class="imagebox"><img alt="žmogus" src="/img/man.jpg" style="width:210px;height:210px" /><br /><br />Žmogus</div>
</div>