Agonija.eu puslapio pokalbių kambario taisyklės.

.	Viešosios taisyklės	Moderatorių taisyklės ir instrukcijos

.	Reklama

.	1. Draudžiama reklamuoti bet kokį kitą internetinį žaidimą.	Jei puslapis reklamuojamas vieną kartą, iškart tyla, bet trumpalaikė. Jei puslapis reklamuojamas daug kartų, spamo formoje - tyla dedama ilgesniam laikotarpiui. Už šios taisyklės pakartotinius pažeidimus dedamos didesnės nuobaudos, kurių didžiausia - uždrausta prieiga prie žaidimo. Chato išvalymas privalomas.

.	2. Draudžiama dėti referalus (linkus, kurių paspaudimas atneša naudos kam nors, pvz, kolonijos augimas ar kitas).	Už įdėtą referalą nedelsiant dedama tyla neilgam laikui. Už pasikartojančius pažeidimus ilginama tyla. Chato išvalymas privalomas

.	3. Draudžiama dėti nuorodas į puslapius su nepadoriu turiniu (pornografija, žiaurūs vaizdai, galintys žaloti vaikų psichiką).	Už pirmą kartą - tyla. Už antrą kartą ilgesnė tyla. Už tolimesnius kartus tylos laikas žymiai pailginamas. Jei tai nepadeda, ir matoma, kad vartotojas piktybiškai pažeidinėja taisyklę, galimas prieigos prie žaidimo uždraudimas. [Chato išvalymas būtų neblogai]

.	4. Draudžiama reklamuoti prekes ar paslaugas, ką nors pardavinėti ar bandyti pirkti	Už pirmą kartą įspėjimas. Už antrą kartą trumpa tyla. Už pasikartojimus - ilgesnės tylos. [Chato išvalymas irgi galimas]

.

.	NETiketas

.	1. Draudžiama rašyti pakartotinio ar panašaus turinio žinutes daug kartų.	Jei vartotojas parašo kelias eilutes paeiliui vienodas, tai nieko (chato apsauga tam skirta prižiūrėti). Jei matote, kad tas pats tekstas rašomas daug kartų iš eilės arba tas pats per tą patį yra rašoma nuolat, kas 5/10/15 ir pan. minučių - įspėjimas, kad liautųsi. Jei įspėjimo nesiklausoma - dedama trumpalaikė tyla. Jei toks pats nusižengimas kartojamas kitą dieną, po kelių dienų ar po ilgesnio laiko tarpo - baudžiama kaip už pirmą kartą. Jei vartotojas 10 kartų pakartoja šitą pažeidimą mėnesio laikotarpyje - dedama ilgesnė tyla.

.	2. Draudžiama rašyti vien tam, kad būtų atkreiptas dėmėsys į save.	Vertinimo sistema panaši kaip ir pirmo punkto. Rašymas vien tam, kad būtų atkreiptas dėmesys į save - tai toks rašymas, kai kalbamos nesąmonės, arba panašus atvėjis kaip buvo minėta forume, kai vartotojas apsimetinėja, kad pardavinėja daiktus ir normaliai bendrauja, nors puikiai jaučiamas tas jo apsimetimas (čia reik labai atsargiai vertinti. jei yra tikimybė, kad vartotojas nekaltas - geriau nebausti arba pasiaiškinti)

.	3. Draudžiama per dažnai dėti įvairių puslapių, sumedžiotų ar gautų daiktų nuorodas ar panašiai teršti pokalbių kambarį	Jei chate vienu metu matomos 7 ir daugiau nuorodos į kokius nors puslapius arba parduodamus daiktus - duodamas įspėjimas. Jei įspėjimo nesilaikoma - dedama tyla. Jei ir tai nepadeda, tylos laikas ilginamas.

.	4. Draudžiama rašyti didžiosiomis raidėmis - internete tai laikoma šaukimu.	Už skainių ar frazių rašymą didžiosiomis raidėmis duodamas įspėjimas. Jei įspėjimo nesilaikoma - trumpa tyla. Jei ir toliau nesilaikoma - tyla ilginama.

.	5. Draudžiama rašyti "po vieną" žodį eilutėje	Kadangi sunku susigaudyti chate ir taip, tai patartina rašyti normaliomis frazėmis ar sakiniais. Jei matoma, kad vartotojas vis rašo po žodį ar du į eilutę, ir taip daug eilučių iš eilės, iš kurių galima sudėti sakinį, ir tai sunkindamas bendravimą - jam duodamas įspėjimas. Jei reikia keli. Tais atvejais, kai vartotojas piktybiškai nereaguoja į perspėjimus - trumpa tyla. Bet geriau vengti jos dėjimo. Reik turėti omenyje, kad sunku greitai perprasti rašyti ne trumpom frazėm, o ilgesnėm.

.	6. Venkite rašyti jums vieniems suprantama kalba ar koduote.	Už neaiškios formos kalbas perspėjimas. Nepaisant perspėjimo - trumpa tyla. Jei ir jos neklausoma - tyla ilginama

.

.	Su žaidimu susijusios

.	2. Draudžiama daug kartų reklamuoti tą patį/tuos pačius daiktus	Daiktą galima pareklamuoti kelis kartus. Tačiau ne daugiau kaip ~5 kartus. Taip pat jei pokalbių lange matoma ankstesnė reklama ir yra dedama vėl to pačio daikto reklama - tai jau per dažnas reklamavimas. Baudos įspėjimas > trumpa tyla > po daugybės kartų pažeidimo tylos ilginamos.

.	3. Jei norima pademonstruoti, kiek turi daiktų ar panašiai, tai galima daryti tik bendrame chate, bet su sveiku protu. Kitais atvejais tai bus laikoma kambario teršimu	Jei 90% (paskaičiuoti iš akies :)) lango yra vien nuorodos - dėti trumpą tylą su įspėjimu. ilginti tylą esant pakartotiniems pažeidimams.

.



.	Kitos

.	1. Draudžiama diskutuoti politinėmis temomis	Bet kokios diskusijos (kirkilas geriau už kubilių, kubilius geriau už adamkų, socialkažkas geresni už liberalkažką ir panašaus tipo) apie politiką yra baudžiamos trumpa tyla. Jei nepadeda - ilgesne. Nedraudžiama diskutuoti apie kokį nors politinį sprendimą - pvz alkoholio reklamos uždraudimą ar panašiai, bet tai turi būti daroma blevyzgose. Tačiau tik iki tol, kol nepradedamos diskusijos kas geresni o kas blogesni ir panašiai.

.	2. Dradžiamos religinės diskusijos	Bet kokia religinė diskusija lyginant ar panašiai svarstant kelias religijas. Savo religijos kelimas virš kitų religijų ir t.t. Tačiau nedraudžiama aptarti tam tikros religijos aspektus. Pvz, kodėl Islamiečiai nevalgo kiaulienos, tačiau tai galima aptarinėti tik blevyzgose

.	3. Draudžiamas antisemitizmas, rasizmas ir kitokie žmogaus teises žeidžiantys pasisakymai.	Visiškai draudžiama. Bausmės pradžiai įspėjimas. Nesilaikant jo - iškart ilga tyla.

.	4. Draudžiama naudoti sovietų, fašistų, kitų totalitarinių ar panašių rėžimų simbolikos, atributikos, terminologijos ir t.t.	Visiškai draudžiama. Iš pradžių įspėjimas. Vėliau trumpa tyla. Palaipsniui ilginti.

.	5. Draudžiama per daug keiktis ar kitaip nepadoriai kalbėti	Jei vartotojas nuolat keikiasi, įspėti jį. vėliau uždėti trumpą tylą. jei ir toliau nereaguoja - dėti ilgą tylą. jei vartotojas kartais nusikeikia, jam išsprūstąkoks žodis, nieko nesakyti. Vėliau matant, kad tai kartojasi ir gana dažnai imtis minėtų sankcijų.	Robotas leidžia 6 minučių laikotarpyje pavartoti 2 keiksmažodžius. Tad jeigu keiksmažodis yra kito žaidėjo įžeidimas, arba vienas vartotojas vienam lange jų pavartojo daugiau kaip 2 (bet kokia forma, kadangi robotas nėra žmogus, ir gali nepastebėti), dėti tylą. Jeigu abejojama ar keiksmažodis grubus, dėti įspėjimą.

.	5.DRAUDŽIAMOS bet kokios diskusijos apie moderatorių sprendimus ir jų aptarimai. Tai galima aiškintis privačiai. Tačiau nedraudžiama kalbėti apie žaidimo taisykles, kitus žaidimo kūrimo aspektus, kurie yra žaidimo kūrėjų įtraukti į žaidimą.	Už svarstymą, kad tam ir anam neteisingai uždėtas banas o tam teisingai iš karto trumpa tyla. Modams taip pat draudžiama kalbėti apie savo sprendimus. Sprendimas lieka tarp modo ir nubaustojo vartotojo. Jie turi asmeniškai ir aiškintis.	Visi vartotojai turi teisę argumentuotai atrašyti į gautą PM, kuriame matys tikslų laiką, 30 paskutinių žinučių išklotinę, bei moderatorių uždėjusiį tylą su paaiškinimu), kuris nukeliaus administratoriui į dėžutę ir adminui į dėžutę, ir adminas išnagrinės ad mdas neviršijo savo įgaliojimus. Adminas sakitys tik argumentuotus laiškus

.	6. Draudžiamas moderatoriaus darbo imitavimas, nurodinėjimas kas ir kam turi dėti baną ir panašūs dalykai.	bauda iš karto įspėjimas, vėliau tyla.

.	7. Draudžiama įžeidinėti kitus vartotojus	už lengvą įžeidimą (kvailys, nesveikas ir pan.) įspėjimas. už sunkų įžeidimą (rūsiški pavadinimai iš s,k š ir t.t. raidžių, ar atitinkami lietuviškį) trumpa tyla iš karto. jei nepadeda dedama ilgesnė

.		Įspėjimus dalinti patartina privačiomis žinutėmis. Vartotojo problema, jei jis jos nepastebėjo. Viešiai chate geriau nieko nerodyti. Taip pat panaikinti tylos uždėjimo vaizdavimą chate, kad kiti žmonės nekeltų triukšmo pamatę jei kažkam uždėta tyla.	Realizuosiu galimybę įspėti tik konkretų vartotoją.

.		Taip pat naujas bausmės būdas - mažinti darbo minutes.

.		Taip apt galima nuimti aptirties. Kadangi nukritus lygiui vartotojo keletą daiktų beturės tik 50% statusu, tai bus labai rimta bausmė