<p>Žaidimo plėtojimui neužtenka gerų norų ir pastangų. Dar reikia ir lėšų serveriui, bei kitos finansinėms reikmėms. Kadangi tai nėra pigu, prašau jūsų, jeigu patiko šis žaidimas, paremkite. Kaikas per dieną daugiau išleidžia bulvių traškučiams. Be to, perkat ir žaidimų kurie kainuoja po 20lt ir daugiau kurie po mėnesio nusibosta. O litas po lito, gali ne tik serverio išlaidas padengti. Be to, kaip atlygį jūs gausite keletą nanų kreditų, kuriuos galėsite panaudoti žaidime.</p>
<p>Beabejo yra keli parėmimo būdai:</p>

<h2 style="margin-top:13px;">Bankas</h2>

<? /*
<p>
Banko sąskaitos duomenys<br>
Sąskaitos kodas: <b>LT477300010106133991</b><br>
Gavėjas: <b>ANDRIUS SEMIONOVAS</b><br>
Bankas: <b>Hansabankas</b><br/>
SWIFT/BIC kodas: <b>HABALT22</b><br />
Įmokos paskirtis: '<b><?=$this->name?></b>'
</p> 

<p>Pervesdami būtinai parašykite įmokos paskirtį. Pervedę parašykite laišką admin@agonija.eu kad patvirtinčiau jūsų pavedimą. Priešingu atveju gali šiek tiek užtrukti. Be to, sąskaitas peržiūriu nevisada, tad nano kreditus nevisada pervesiu iškarto. Už 1 litą gausite 2 nanokreditus. Pervedant pinigus užsienio valiuta, nano kreditų gausite pagal tuo metu galiojančius "swedbank" kursus</p>
*/?>  
<h2 style="margin-top:13px;">SMS</h2>

<p>
<b>SMS</b><br>
Raktažodis: '<b>AGO1 <?=$this->name?></b>' (be kabučių).<br>
Numeris: <b>1656</b><br>
Kaina: <b>1LT</b><br>
Nano kreditai:<b>1</b><br>
Tinklai: <b>Visi Lietuvos Operatoriai</b><br><br>

Raktažodis: '<b>AGO2 <?=$this->name?></b>' (be kabučių).<br>
Numeris: <b>1654</b><br>
Kaina: <b>2LT</b><br>
Nano kreditai:<b>2</b><br>
Tinklai: <b>Visi Lietuvos Operatoriai</b><br><br>

Raktažodis: '<b>AGO5 <?=$this->name?></b>' (be kabučių).<br>
Numeris: <b>1679</b><br>
Kaina: <b>5LT</b><br>
Nano kreditai:<b>5</b><br>
Tinklai: <b>Visi Lietuvos Operatoriai</b><br><br>

Raktažodis: '<b>AGO10 <?=$this->name?></b>' (be kabučių).<br>
Numeris: <b>1679</b><br>
Kaina: <b>10LT</b><br>
Nano kreditai:<b>10</b><br>
Tinklai: <b>Visi Lietuvos Operatoriai</b>
</p>

<h2 style="margin-top:13px;">Paypal</h2>

<p>
Pašto adresas:<b>admin@neworldwar.com</b><br />
1EUR=6 nano kreditų<br /><br />

Kol kas tai visi įmanomi mokėjimo būdai, easnt poreikiu didinsiu šį skaičių.<br><br>
</p>

<h2>Ačiū visiems parėmusiems, arba kurie dar tik žada paremti.</h2>